version: '3.8'

services:
    node:
        build:
            context: .
            args: # from .env file
                NODE_VERSION: ${NODE_VERSION}
                NPM_VERSION: ${NPM_VERSION}
                HTTP_PORT: ${HTTP_PORT}
        ports:
            - ${HTTP_PORT}:${HTTP_PORT}
        restart: unless-stopped
        volumes:
            - .:/home/node/buymeadr.ink:delegated
            - /home/node/buymeadr.ink/node_modules
