version: '3.8'

services:
    back:
        container_name: nest
        build:
            context: .
            args: # from .env file
                NODE_VERSION: ${NODE_VERSION}
                NPM_VERSION: ${NPM_VERSION}
                PORT: ${PORT}
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            FRONT_URL: ${FRONT_URL}
            STRIPE_SECRET_API_KEY: ${STRIPE_SECRET_API_KEY}
        command: [ "npm", "run", "start:dev" ]
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/home/node/buymeadr.ink:delegated
            - /home/node/buymeadr.ink/node_modules
